CRON:
  RememberMe:
    # Cookie name and lifetime
    cookie:
      name: 'remember-me'
      lifetime: 2592000
    # Form field names for the login form including the remember-me checkbox,
    # used in CRON\RememberMe\Security\Authentication\Token\UsernamePasswordWithRememberMe.php.
    # Configure to use that token with your authentication provider.
    loginFormFields:
      username: '__authentication.CRON.RememberMe.Security.Authentication.Token.UsernamePasswordWithRememberMe.username'
      password: '__authentication.CRON.RememberMe.Security.Authentication.Token.UsernamePasswordWithRememberMe.password'
      rememberMe: '__authentication.CRON.RememberMe.Security.Authentication.Token.UsernamePasswordWithRememberMe.rememberMe'
    # Class name implementing RememberMeAuthenticationProcessorInterface. See interface for more information.
    rememberMeAuthenticationProcessorClassName: 'CRON\RememberMe\Security\Authentication\RememberMeAuthenticationProcessor'
