Neos:
  Flow:
    security:
      authentication:
        providers:
          'RememberMeAuthenticationProvider':
            provider: CRON\RememberMe\Security\Authentication\RememberMeProvider
            token: CRON\RememberMe\Security\Authentication\Token\RememberMe
            requestPatterns:
              'CRON.RememberMe:NeosFrontend':
                pattern: CRON\RememberMe\Security\Authentication\NeosRequestPattern
                patternOptions:
                  matchFrontend: true